export const SET_CARD_USER_NAME = 'SET_CARD_USER_NAME';
export const SET_CARD_NUMBER = 'SET_CARD_NUMBER';
export const SET_CARD_EXPDATE = 'SET_CARD_EXPDATE';
export const SET_CARD_WHOLE = 'SET_CARD_WHOLE';
export const CARD_RESET = 'CARD_RESET';